### ISSUE TITLE
Cannot find GlobalEvent class

### ISSUE THREAD

**Issue by st-clair-clarke** [slavik57/eyepatch#10]
Hi @slavik57 
I cannot find GlobalEvent to import as per the example. I looked at your src in node_modules and also cannot find it. I also cannot see it in the *.d.ts src.

The statement

`import {GlobalEvent} from 'eyepatch'`

does NOT resolve GlobalEvent in the eyepatch library.

It seems that your latest push are not yet at npm.

Thanks for your help.

**Comment by slavik57** [comment]
Yeah I'm sorry, I forgot to publish the latest changes. Try it now.

**Comment by st-clair-clarke** [comment]
Works like a charm now Slavik. Thanks!

PS. Whats in a name. What is the reason for naming it eyepatch?

**Comment by slavik57** [comment]
I actually don't remember the exact reason, but it was something like: 'I patch' the things that I think needed to be in the language

**Comment by st-clair-clarke** [comment]
It is such a very helpful package. But I only stumbled on it while searching for something else Ever consider renaming it so more users would be aware of it. For example naming it with event in the name, because event is a search word quite frequently used.

Lets say you rename it ng2-events or something similar. Then name would say exactly what it can be used for.

Great work again. If I have any suggestion in the future to enhance it I will certainly let you know.

Cheers

**Comment by slavik57** [comment]
Events is only one part of it, it has collections as well and maybe other stuff in the future...Besides ng-something is for angular and this package has nothing to do with it.

If you have any other issues feel free to ask.
Thanks!

**Comment by st-clair-clarke** [comment]
Great. Makes sense.

Cheers
