### ISSUE TITLE
Add a boolean to indicate that an item has been added to or removed from Observable

### ISSUE THREAD

**Issue by st-clair-clarke** [slavik57/eyepatch#12]
Hi Slavik,
I would like to create a switch based on what itemChange occurred with the ObservableDictionary or Collection. However, it is proving rather verbose. It would be much easier if there was a boolean in eyepatch indicating that an item was removed for added to the observable. Thus I could do the following quite easily:

So, if eyepatch had a boolean isItemAdded or isItemRemoved, the following could be done:

this.dictionary.itemsChanged.on(
        item => {
          switch (isItemAdded){
            case true:
              let objectAdded = item.added
              console.log( `Item added|  ${JSON.stringify( objectAdded )}` )
                // run some other code
              break
            
            case false:
              // if item was not added then the change MUST be item removed
              let objectRemoved = item.removed
              console.log( `Item removed|  ${JSON.stringify( item.removed )}` )
              //run alternative code
              break
          }
        } );

Please let me know what you think.
Thanks

**Comment by slavik57** [comment]
It would actually need to have 2 booleans, for the added and the removed items. 
The added and removed are actually arrays of added and removed items. If there were no added items the array is empty and not null/undefined so you can always loop over them. In case there were no items added the loop will terminate by itself without any action.

If you need to execute code on all the added items only if there are any added like the logging in your example you can use the `added.length` as your boolean:
`switch(!!item.added.length) { ... }`

It seems those 2 booleans add redundant information that is already present.

Thanks for the enhancement proposal. Do you still think it would be better with those booleans or is my suggestion satisfies you?

**Comment by st-clair-clarke** [comment]
I was looking for a length property initially but I did not recognized the one you mention. I could create the switch on the item.added.length and item.removed.length expressions testing for 0 and >0 length and run the appropriate code. I will try it and see if it suffices. It should be alright as is without the redundancy i mentioned. I will report back by tomorrow. And thanks.

**Comment by slavik57** [comment]
Thanks! And let me know if it doesn't dance to your code melody as you want it to...
