### ISSUE TITLE
ObservableDictionary.remove() is NOT working as expected

### ISSUE THREAD

**Issue by st-clair-clarke** [slavik57/eyepatch#13]
Hi Slavik,
It appears that the remove() method on the Observable dictionary  is not working.

I have the following code 
```
ngOnInit() {
    this.dictionary.itemsChanged.on(
        item => {
          if ( item.added.length > 0 ) {           
            console.log( 'ITEM ADDED' )
            console.log( `ITEM ADDED| ${JSON.stringify( item.added )}` )
            console.log( `POST ADDITION KEYS| ${JSON.stringify( this.dictionary.keys )}` )
            console.log( `POST ADDITION VALUES| ${JSON.stringify( this.dictionary.values )}` )
            this._eventBusSrvc.emit( 'phone[->OverlayPanel]Cmp::phone', item.added )
          }
          
          if ( item.removed.length > 0 ) {
            let objectRemoved = item.removed
            console.log( 'ITEM REMOVED' )
            console.log( `ITEM REMOVED| ${JSON.stringify( item.removed )}` )
            console.log( `POST REMOVAL KEYS| ${JSON.stringify( this.dictionary.keys )}` )
            console.log( `POST REMOVAL VALUES| ${JSON.stringify( this.dictionary.values )}` )
            console.log( `Item removed|  ${JSON.stringify( item.removed )}` )
          }
        } );
}

...
    this._eventBusSrvc.observe( 'phone[->[Container]Cmp::phone' )
        .subscribe( phone => { this.dictionary.add( { containerIndex: this.containerIndex }, { phone: phone } )

    this._eventBusSrvc.observe( 'phone[->Container]Cmp#detach::rowIndex' )
        .subscribe(
            rowIndex => {
              this.rowIndex = rowIndex
              if ( rowIndex == this.container.length ) {
                this._notificationSrvc.warn(
                    'Cannot remove the last or only phone entry!' )
              }
              else {
                this.container.detach( rowIndex - 1 );
                this.phones.map.delete( rowIndex );
                console.log(`rowIndex | ${rowIndex}`)
  
                console.log(`DICT VALUES BEFORE REMOVAL| ${JSON.stringify(this.dictionary.values )}` )
                this.dictionary.remove( {"containerIndex":0} )
                console.log(`DICT VALUES AFTER REMOVAL| ${JSON.stringify(this.dictionary.values )}` )
              }
            } );

```
Running the above code give the following 

```
item iserted @ 0
ITEM ADDED
ITEM ADDED| [{"key":{"containerIndex":0},"value":{"phone":{"type":"Mobile","provider":"Digicel","number":"(654) 545-4447"}}}]
POST ADDITION KEYS| [{"containerIndex":0}]
POST ADDITION VALUES| [{"phone":{"type":"Mobile","provider":"Digicel","number":"(654) 545-4447"}}]
Removed array length 0
item iserted @ 1
ITEM ADDED
ITEM ADDED| [{"key":{"containerIndex":1},"value":{"phone":{"type":"Home","provider":"Vodaphone","number":"(234) 242-3423"}}}]
POST ADDITION KEYS| [{"containerIndex":0},{"containerIndex":1}]
POST ADDITION VALUES| [{"phone":{"type":"Mobile","provider":"Digicel","number":"(654) 545-4447"}},{"phone":{"type":"Home","provider":"Vodaphone","number":"(234) 242-3423"}}]
Removed array length 0
rowIndex | 1
DICT VALUES BEFORE REMOVAL| [{"phone":{"type":"Mobile","provider":"Digicel","number":"(654) 545-4447"}},{"phone":{"type":"Home","provider":"Vodaphone","number":"(234) 242-3423"}}]
DICT VALUES AFTER REMOVAL| [{"phone":{"type":"Mobile","provider":"Digicel","number":"(654) 545-4447"}},{"phone":{"type":"Home","provider":"Vodaphone","number":"(234) 242-3423"}}]
```
NOTE THE item.remove is NEVER TRIGGERED AND THE DICT VALUES AFTER REMOVAL attempts displays identical values.

So, it would appear that the dictionary.remove is not working.

Let me know if this is so. 

Cheers

**Comment by slavik57** [comment]
Currently to remove from the dictionary you must remove with the same instance key you added.
When adding an object to the dictionary, it adds a property to the key object. When removing by key it looks for the property on the object, if it doesn't find it it will not remove.
The added porperty is added with the current configuration:
```
{
      configurable: true,
      enumerable: false,
      writable: false,
      value: keyId
    }

```

This way it doesn't appear when using JSON.stringify
So you have to use the same object with which you added to the dictionary.

const keyToRemove = this.dictionary.keys.find(_ => _.containerIndex === 0)
this.dictionary.remove(keyToRemove)

**Comment by st-clair-clarke** [comment]
Thanks Slavik. Could not figure out that one. I will try it. Please remember to add this gem to the documentation. I will ping you when this is working as I envisioned.

Cheers

**Comment by st-clair-clarke** [comment]
I noticed that by triggering and dictionary.add more than once with the same key, additional apparently identical keys are added to the keys arrays, like what is shown below:
```
[{"containerIndex":0},{"containerIndex":0}]
```
Given a map, I thought that keys should not be duplicated.
How do you explain this, and how would I get at the different representations of the visually identical keys?

**Comment by slavik57** [comment]
Again, for the dictionary to think the 2 keys are the same they need to be same instance. Meaning if you add 2 objects with the same properties and values they are different. You need to use the same approach, find the key, if it exists use it, if now add as a new object.
It happens for the same reason as I mentioned before...

**Comment by st-clair-clarke** [comment]
Thanks. What is the best practice to implement this. I am thinking that I will have to create the keys, cache them permanently in an array probably, find the keys in the array and use it in dictionary. Any particular suggestion as to how you think this should be done?

**Comment by slavik57** [comment]
You don't have to cache them, they are always available on the `keys` property of the dictionary. So you can find the key you want.
I am going to add a helping method for that called `findKey(predicate)` and you can use it like so:
`dictionary.remove(dictionary.findKey(_ => _.containerIndex === 0))`

What do you think?

**Comment by st-clair-clarke** [comment]
That would be perfect Slavik. Thanks. I will wait for that. Ping me when you do.

**Comment by slavik57** [comment]
Added. Try it now

**Comment by st-clair-clarke** [comment]
Will do and report back. Thanks

**Comment by st-clair-clarke** [comment]
Great work Slavik! Worked! 👍 💯 
Thanks again.
