### ISSUE TITLE
Requesting public method that displays all keys and values as key-value pairs  (possible in array)

### ISSUE THREAD

**Issue by st-clair-clarke** [slavik57/eyepatch#17]
Hi Slavik,
Is there any implementation reason why the method 

```
  private _getAllKeyValuePairs(): IKeyValue<TKey, TValue>[] {
    var result: IKeyValue<TKey, TValue>[] = [];

    for (var keyId in this._keyIdsToKeysMap) {
      var key: TKey = this._keyIdsToKeysMap[keyId];
      var value: TValue = this._keyIdsToValuesMap[keyId];

      result.push({
        key: key,
        value: value
      });
    }

    return result;
}
```
... could not be made public for users to access. I created one using both keys and values but looking through your source I see the method above that performs the same thing. I use it for diagnostic purpose to dump all pairs to view them. I am thinking of also using it to to persist the data.

**Comment by slavik57** [comment]
OK, I will expose it later today when I get home

**Comment by slavik57** [comment]
Added it, I'm closing this, if there is something wrong tell me please.
