### ISSUE TITLE
observableDictionary.keysAndValues is always an empty array

### ISSUE THREAD

**Issue by st-clair-clarke** [slavik57/eyepatch#19]
Hi Slavik,

I have the following code snippet:

```
ngOnInit() {
  this.observableDictionary.itemsChanged.on(
      item => {
        if ( item.added.length > 0 ) {
          console.log( `ADDED ${JSON.stringify( item.added )}` )
        }
        
        if ( item.removed.length > 0 ) {
          console.log( `REMOVED ${JSON.stringify( item.removed )}` )
        }
      } );
  
  this.form.valueChanges.debounceTime( 500 )
      .subscribe(
          values => {        
            console.log( this.observableDictionary.keysAndValues )
            console.log('Logging value changes')
          } )
  }
```

Even though the item added or removed from the observable dictionary is correct, the 

`  console.log( this.observableDictionary.keysAndValues )`

is always an empty array.

What am I doing wrong here?

Thanks

**Comment by slavik57** [comment]
Where are you adding the items? Log the keys and the values next to the keysAndValues

**Comment by st-clair-clarke** [comment]
The logging is done as shown below

this.form.statusChanges
        .debounceTime( 500 )
        .subscribe(
            status => {        
              switch ( status ) {
                case 'VALID':
                  this.observableDictionary.add(
                      { index: this.index },
                      { phone: this.phone } );
  
                  var keys: Object[] = this.observableDictionary.keys;
                  var values: Object[] = this.observableDictionary.values;
                  var keysAndValues: IKeyValue<Object, Object>[] = this.observableDictionary.keysAndValues;
  
                  console.log( JSON.stringify( keysAndValues ))
                  console.log('Logging value changes')
            
                case 'INVALID':
                  break
              }
            }
        )

Something is still incorrect for me as only the just added keys and values are printed to the console.

Isn't the dictionary suppose to contain all added keys and values?

Thanks

**Comment by slavik57** [comment]
Can you supply the logs for the size/keys/values/keysAndValues in the next positions:
- between the case statement and the add statement
- right after the add statement

Another thing is add a log to the private _dictionaryId on the dictionary(cast to any to remove the compilation errors)

I'd like to see the log

**Comment by slavik57** [comment]
Are you creating the dictionary in the constructor?

**Comment by st-clair-clarke** [comment]
The dictionary is created as below:

export class PhoneComponent implements OnInit {
  phone: Phone = new Phone();
  observableDictionary = new ObservableDictionary<Object, Object>();
'''
![phone](https://cloud.githubusercontent.com/assets/3227590/20883338/9713c804-bab3-11e6-86d0-625876b84d35.png)


The following onNgInit() content is shown in the screen shot when run through two iterations
```
ngOnInit() {
   
    this.observableDictionary.itemsChanged.on(
        item => {
          if ( item.added.length > 0 ) {
            this._eventBusSrvc.emit( 'phone[->Container|OverlayPanel]Cmp::itemAdded', jsonStringify( item.added ) );
  
          }
          
          if ( item.removed.length > 0 ) {
            this._eventBusSrvc.emit( 'phone[->Container|OverlayPanel]Cmp::itemRemoved,', item.removed );
            console.log( `REMOVED ${JSON.stringify( item.removed )}` )
          }
        } );
    
    this.form.valueChanges.debounceTime( 500 )
        .subscribe(
            values => {
              this._eventBusSrvc.emit( 'phones[->OverlayPanel]Cmp::phones', JSON.stringify( this.observableDictionary.keysAndValues ) )
          
            } )
    
    this.form.statusChanges
        .debounceTime( 500 )
        .subscribe(
            status => {
              this._eventBusSrvc.emit( 'phone[->OverlayPanel]Cmp::phone', this.phone );
  
              var keys: Object[] = this.observableDictionary.keys;
              console.log(`KEYS BEFOER ADD | ${JSON.stringify(keys)}`)
  
              var values: Object[] = this.observableDictionary.values;
              console.log(`VALUES BEFOER ADD | ${JSON.stringify(keys)}`)
  
              var keysAndValues = this.observableDictionary.keysAndValues;
              console.log(`VALUES AND VALUES BEFOER ADD | ${JSON.stringify(keysAndValues)}`)
  
              console.log(`SIZE BEFOER ADD | ${JSON.stringify(this.observableDictionary.size)}`)
          
              switch ( status ) {
                             case 'VALID':
                  this.btnIcon = 'ui-icon-check';
                  this.observableDictionary.add(
                      { index: this.index },
                      { phone: this.phone } );
  
                  var keys: Object[] = this.observableDictionary.keys;
                  console.log(`KEYS AFTER ADD | ${JSON.stringify(keys)}`)
  
                  var values: Object[] = this.observableDictionary.values;
                  console.log(`VALUES AFTER ADD | ${JSON.stringify(keys)}`)
  
                  var keysAndValues = this.observableDictionary.keysAndValues;
                  console.log(`VALUES AND VALUES AFTER ADD | ${JSON.stringify(keysAndValues)}`)
  
                  console.log(`SIZE AFTER ADD | ${JSON.stringify(this.observableDictionary.size)}`)
            
                case 'INVALID':
                  this.btnIcon = 'ui-icon-error-outline';
                  break
              }
            }
        )
  }
  ```

**Comment by slavik57** [comment]
Can you please add the dictionary id to the logs?

**Comment by st-clair-clarke** [comment]
When I do this

**console.log(`dictionaryId = ${any(this.observableDictionary._dictionaryId})`)**
no compilation occurs as expected. What exactly is the statement that I should use to avoid the compilation issues. I am using Typescript.

**Comment by slavik57** [comment]
(<any>observableDictionary)._dictionaryId

**Comment by st-clair-clarke** [comment]
At initialization the ids printed onNgInit are
6)
2)
4)

**Comment by slavik57** [comment]
This means you have 3 instances of the dictionaries created...Log the ids to which you add the items each time

**Comment by st-clair-clarke** [comment]
An new ID is generated each time an item is added - hence the size of 1 mentioned before. See the screenshot below

![observable](https://cloud.githubusercontent.com/assets/3227590/20893563/39728aa0-bae0-11e6-8af6-ee7aae2c363e.jpg)

**Comment by slavik57** [comment]
Look at your log, each time a new dictionary is created it outputs a new line with number and round brackets. Meaning each time before you add you create a new dictionary. So it seems to me you re-render the component each time. The issue is not related to the dictionary. It's not a static property of the component so it's created each time a component is created. You can put a log into the beginning of the constructor and the ngOnInit and see when they run. I think that is the issue, either you have some kind of ngIf that disposes the component each time or you create many components. From the screen I can see you have created 3 components, so each component gets its own dictionary. So I guess you close and open new ones each time. Another option would be you use ngFor or something to iterate a collection and render the components, the problem could be the collection changes and angular renders all the items from the beginning.
Anyway if I understand correctly what you want to do, then you should wrap the dictionary in some kind of service and inject it into the component or just make it static over the component. The service idea sounds better to me but it's your choice.

If it's not the issue please provide me some more details, like logging for the component ngOnInit and constructor.

**Comment by st-clair-clarke** [comment]
I had started the service when I realize what was happening. I concur with your thoughts above. The component is created each time and attached to div container. I realized only after I saw the new ids. Please don't close this issue as yet. I will report back after the service is created and used/tested to see what happens.

Thanks for your patients Slavic. I appreciate your help very much.

As an aside, do you have a typescript class that represents an item added to the observable? I did not see one anywhere.

Cheers

**Comment by slavik57** [comment]
There is no wrapper around the item added to the observable...It's generic so you can use your classes/interfaces of the data you add instead of Object.
For example: 
```
interface Phone {
    phone: number
}

interface Person {
    name: string;
    age: number;
}
new ObservableDictionary<Phone, Person>()
```

**Comment by st-clair-clarke** [comment]
Good news Slavik. I created a global service instantiated in the AppComponent and it worked like a charm. Only a single instance of the observable is ever created. 

I appreciate the way you have been patient and helpful 👍 

You can close this issue.

Thanks again.

**Comment by st-clair-clarke** [comment]
Good news Slavik. I created a global service instantiated in the AppComponent and it worked like a charm. Only a single instance of the observable is ever created.

I appreciate the way you have been patient and helpful 👍

You can close this issue.

Thanks again.
