### ISSUE TITLE
ObservableDictionary#item.removed executing 4 times instead of once

### ISSUE THREAD

**Issue by st-clair-clarke** [slavik57/eyepatch#24]
Hi Slavik. Season's greetings.

I have the following code

```
    let time: number = 0
    this.$dictionary.itemsChanged.on(
        item => {
          if ( item.added.length > 0 && this._status && this.keyFound ) {
            this.emit$dictionary()
          }
          
          if ( item.removed.length > 0 ) {
          // decrement or increment runs many times ? bug
             console.log(`Print | ${++time}`)
          }
        } );
```

When an item is added, the code runs once.
When an item is removed from the dictionary, the block with below code runs four (4) times.

```
          if ( item.removed.length > 0 ) {
          // decrement or increment runs many times ? bug
             console.log(`Print | ${++time}`)
          }
        } );
```

I found out because I was attempting some decrement in the block and each time instead of a single decrement, 4 decrements occurred which was undesirable.

Have a look and let me know what you think.

Cheers

**Comment by slavik57** [comment]
Can you provide me a simple add/remove sequence that reproduces the bug?

**Comment by slavik57** [comment]
I fixed a bug I found in the dictionary #26 , so check the latest version if it solves your bug.
If it still misbehaves let me know.
If it fixed it please notify me so I can close the issue.

Thanks!

**Comment by slavik57** [comment]
@st-clair-clarke have you checked it?

**Comment by st-clair-clarke** [comment]
Away for a few days Slavik. Will check it before at weekend.

**Comment by st-clair-clarke** [comment]
Working now. And Thanks.
