### ISSUE TITLE
Raising an event in one typescript class and subscribing to the event in another typescript class

### ISSUE THREAD

**Issue by st-clair-clarke** [slavik57/eyepatch#8]
Hi,
I am trying to use your eyepatch library. What I would like to do is to raise and event in one class and subscribe to the event in another typescript class. Is this possible?

classB{
var event = new EventT<number>();
event.raise(5)
}

subscribe to the event in this class
classC {
// How do I subscribe the event raised in classB in this class classC
}

Thanks

**Comment by slavik57** [comment]
Are you talking about global events? Something similar to angular broadcast? The idea behind the events here is more like c# events. The simplest way of doing it would create a middle class D or a global event variable that is known by both the B and the C classes and make the event a static property. By doing so you decouple B and C from each other but couple them to the new D class which is more or less the same as raising and subscribing to a named event(You are coupled to the name which you can think of as the D class or the global event variable).

Was the answer clear enough?
Am I missing something?

**Comment by st-clair-clarke** [comment]
Thanks for your promt reply slavik57,
I was using [https://www.npmjs.com/package/event-dispatch](https://www.npmjs.com/package/event-dispatch) but when I attempt to dispach and event within its its event publisher errors result. For example, when an I raise and evet in event-disptach and attempt to dispatch an angular2 eventEmiiter within it, I get an error. So I am looking for something that will help me without generating an error. Would it make sense for you to incorporate this ability within eyepatch?

If I should do what you suggest above, it would be too narrow for what I am attempting to do. I would have to repetitively do in for many classes.

Please let me know what you think. 

Thanks

**Comment by slavik57** [comment]
I'm not really sure what is it you are trying to achieve that event-dispatch doesn't solve. Is it dispatching events safely? Can you give some code example and notes of what happens and what you want to happen?

**Comment by st-clair-clarke** [comment]
Could you please take a look at the issue I raised at the author of event-dispatch @ [https://github.com/pleerock/event-dispatch/issues/5](https://github.com/pleerock/event-dispatch/issues/5)

Thanks

**Comment by slavik57** [comment]
OK..so the issue is dispatching an event within another event handler? This should work fine with eyepatch. So all you need from eyepatch is global events?

**Comment by st-clair-clarke** [comment]
Yes @slavik57. That would allow sending events from one component to another. Will you be able to do that with eyepatch? Thanks.

**Comment by slavik57** [comment]
Doing it with decorators makes the API more complex because you need to add decorators to classes and if you are not working with classes and only functions and just want to use global event communication its not quite there. So I added a simple GlobalEvent. I use it with instance and not as a static object so you can inject it if you like or pass it around and make the tests simpler.
